### ISSUE TITLE
Working on the build

### ISSUE THREAD

**Issue by cvvergara** [MobilityDB/MobilityDB#85]
(Cleaned up the original message to have the tasks clear
tasks
- [x] make it work locally
- [x] Wait for approval & merge #90 
- [x] organize SQL
- [x] Wait for approval & merge #97 
- [x] organize SRC
- [x] Wait for approval & merge #105
- [x] organize datagen
- [x] Wait for approval & merge #100
- [x] Cleanup Build
- [x] Wait for approval & merge #103

**Comment by cvvergara** [comment]
Looks like the test.cmake is not catching the postgres version found during the build
```
::::::::::::::
tmptest/log/initdb.log
::::::::::::::
/home/vicky/mobilitydb/mobilitydb/cvvergara/test/scripts/test.sh: line 33: initdb: command not found
::::::::::::::
tmptest/log/pg_start.log
::::::::::::::
/home/vicky/mobilitydb/mobilitydb/cvvergara/test/scripts/test.sh: line 47: pg_ctl: command not found
```

**Comment by cvvergara** [comment]
Why the tests need this?
```
    sed -e "s|MODULE_PATHNAME|$SOFILE|g" -e "s|@extschema@|public|g" < $EXTFILE | $FAILPSQL 2>&1 1>/dev/null | tee -a "$WORKDIR"/log/create_ext.log
```

Why doesnt it just do `CREATE EXTENSION mobilityDB

BTW, the generated SQL file lacks the line:
```
\echo Use "CREATE EXTENSION mobilitydb" to load this file. \quit
```

Examples
https://www.postgresql.org/docs/10/extend-extensions.html#EXTEND-EXTENSIONS-EXAMPLE
https://github.com/postgis/postgis/blob/main/extensions/postgis_topology/extlock.sql
https://github.com/pgRouting/pgrouting/blob/main/sql/common/pgRouting-header.sql#L25

**Comment by cvvergara** [comment]
A little improvement :-)
```
Test project /home/vicky/mobilitydb/mobilitydb/cvvergara/build
        Start   1: build
  1/111 Test   #1: build .............................   Passed    0.16 sec
        Start   2: setup
  2/111 Test   #2: setup .............................   Passed    0.02 sec
        Start   3: create_extension
  3/111 Test   #3: create_extension ..................***Failed    0.01 sec
  ```

**Comment by cvvergara** [comment]
Tada!!!!
```
110/111 Test #110: 97_tnpoint_tempspatialrels ........   Passed    0.12 sec
        Start 111: 97_tnpoint_tempspatialrels_tbl
111/111 Test #111: 97_tnpoint_tempspatialrels_tbl ....   Passed    0.11 sec

100% tests passed, 0 tests failed out of 111
```
I finnaly managed to run the tests on my computer

**Comment by cvvergara** [comment]
https://github.com/cvvergara/MobilityDB/actions/runs/1047502412
- [ ] cleanup latest changes

**Comment by estebanzimanyi** [comment]
Wonderful !

Could you please summarize what changes should be done in our code ? Otherwise, if you want, please send a PR with the required changes.

Thanks again for all your efforts !!!

**Comment by cvvergara** [comment]
Ah, this is the beginning, as I could not run the tests on my computer.
Before any change, I need to be able to run in my computer first.
Summary:
Basically have this in such away that Regina can build with postgis 2.5, and from there, try to move to postgis 3

**Comment by cvvergara** [comment]
this is strange: All the tests are passing, but the postgres log is full of errors:
```
2021-07-20 14:11:12.992 CDT [1680775] ERROR:  could not find function "period_gist_decompress" in file "/usr/lib/postgresql/12/lib/libMobilityDB.so"
2021-07-20 14:11:12.992 CDT [1680775] STATEMENT:  CREATE EXTENSION mobilitydb;
2021-07-20 14:11:13.375 CDT [1680892] ERROR:  type "stbox" does not exist at character 8
2021-07-20 14:11:13.375 CDT [1680892] STATEMENT:  SELECT stbox 'STBOX((1.0, 2.0), (3.0, 4.0))';
2021-07-20 14:11:13.375 CDT [1680892] ERROR:  type "stbox" does not exist at character 8
2021-07-20 14:11:13.375 CDT [1680892] STATEMENT:  SELECT stbox 'STBOX Z((1.0, 2.0, 3.0), (4.0, 5.0, 6.0))';
2021-07-20 14:11:13.375 CDT [1680892] ERROR:  type "stbox" does not exist at character 8
```
How can the tests pass if everything is throwing an error?

**Comment by estebanzimanyi** [comment]
The MobilityDB tests explicitly cover the errors. This allows us to cover
the lines of errors in coveralls and achieve the high coverage
(currently 95.991%)

In the test files, for each function there are several tests covering
normal behaviour, and then after a line /* Errors */ all failing behaviour
follows. As an example, the testing for string input of the stbox type
(file 50_stbox.test.sql) is as follows.

-------------------------------------------------------------------------------
-- STbox
-------------------------------------------------------------------------------

SELECT stbox 'STBOX((1.0, 2.0), (3.0, 4.0))';
SELECT stbox 'STBOX Z((1.0, 2.0, 3.0), (4.0, 5.0, 6.0))';
SELECT stbox 'STBOX T((1.0, 2.0, 2001-01-01), (3.0, 4.0, 2001-01-02))';
SELECT stbox 'STBOX ZT((1.0, 2.0, 3.0, 2001-01-01), (4.0, 5.0, 6.0,
2001-01-02))';
[...]

/* Errors */
SELECT stbox 'AAA(1, 2, 3)';
SELECT stbox 'stbox(1, 2, 3)';
SELECT stbox 'stbox((AA, 2, 3))';
SELECT stbox 'stbox((1, AA, 3))';
SELECT stbox 'stbox((,),(,))';
[...]

-------------------------------------------------------------------------------

**Comment by cvvergara** [comment]
Locally in my computer I am getting:
```
mobtest=# create extension mobilitydb ;
ERROR:  could not load library "/usr/lib/postgresql/12/lib/libMobilityDB.so": /usr/lib/postgresql/12/lib/libMobilityDB.so: undefined symbol: lwgeom_hash
```

**Comment by cvvergara** [comment]
This:
```
2021-07-20 14:11:12.992 CDT [1680775] ERROR:  could not find function "period_gist_decompress" in file "/usr/lib/postgresql/12/lib/libMobilityDB.so"
2021-07-20 14:11:12.992 CDT [1680775] STATEMENT:  CREATE EXTENSION mobilitydb;
```
Mean that the library is missing period_gist_decompress, so its not loaded

**Comment by estebanzimanyi** [comment]
> Locally in my computer I am getting:
> 
> ```
> mobtest=# create extension mobilitydb ;
> ERROR:  could not load library "/usr/lib/postgresql/12/lib/libMobilityDB.so": /usr/lib/postgresql/12/lib/libMobilityDB.so: undefined symbol: lwgeom_hash
> ```

As stated in the README.md file and in the documentation

You should also set the following in postgresql.conf:
-----------------------------------------
shared_preload_libraries = 'postgis-2.5'
max_locks_per_transaction = 128
-----------------------------------------

**Comment by cvvergara** [comment]
Interesting that the modification to postgresql.conf is compulsory.
Will ask (linux) packagers about that.

**Comment by estebanzimanyi** [comment]
Another way to see the problem is that the first time a MobilityDB function is executed, the library libMobilityDB is loaded and this requires that the liblwgeom library be loaded as the first step. In the error you mentioned above, while loading the libMobilityDB library without the liblwgeom library, the function lwgeom_hash (called undefined symbol in the error message) is defined in the latter library.

**Comment by robe2** [comment]
@estebanzimanyi  I'm puzzled.  If you are only using liblwgeom-2.5.so why do you need postgis-2.5 library loaded?  All the functions you need should already be in liblwgeom-2.5.so as you are already directly linking to that library.

**Comment by estebanzimanyi** [comment]
> @estebanzimanyi I'm puzzled. If you are only using liblwgeom-2.5.so why do you need postgis-2.5 library loaded? All the functions you need should already be in liblwgeom-2.5.so as you are already directly linking to that library.

I cannot find that library in the directory reported by `pg_config --pkglibdir` which in my case is `/usr/local/pgsql/13/lib`

**Comment by estebanzimanyi** [comment]
@cvvergara Do you have any idea why coverall does not work anymore after the latest PR ?

**Comment by estebanzimanyi** [comment]
Is the file travis.yml still needed ? I think it is redundant with the new workflow.

**Comment by estebanzimanyi** [comment]
> @cvvergara Do you have any idea why coverall does not work anymore after the latest PR ?
> https://coveralls.io/builds/41554152

Same problem with the MobilityDB/develop branch for my last PR
https://coveralls.io/builds/41565546

**Comment by cvvergara** [comment]
Is the file travis.yml still needed ? I think it is redundant with the new workflow.
yeah, but I think you have it linked to the coverage/coveralls

**Comment by cvvergara** [comment]
I do not have any idea of what `coverall` does, let alone why it is not working anymore. Might be because the code is been moved around? but that is just a guess, I don't know what  that CI does

**Comment by estebanzimanyi** [comment]
According to 
https://gcc.gnu.org/onlinedocs/gcc/C-Dialect-Options.html
the option `gnu1x` we put in the CMakeLists.txt 
```
add_definitions(-Wall -Wextra -std=gnu1x -Wno-unused-parameter)
```
is deprecated. Both `gnu11` and `gnu17` work for the current code and no warning is raised. Which should be use ?

**Comment by cvvergara** [comment]
Dont know, right now I havent finished fixing the build and organizing the include & src code, so that is not a topic of this issue.
Please open another issue about the convenient dialects.

**Comment by cvvergara** [comment]
@estebanzimanyi 
A file in src uses an include in point/include
There are 2 choices
1) place all includes under include directory.
2) have a structure like:
```
include
├── general
├── npoint
└── point
```
Option 2 requires that changes like:
From:
```
#include "doublen.h"
```
to:
```
#include "general/doublen.h"
```
Option 1 does not, but the include looks unorganized.
I am going with option 2 which is organized (as I am organizing code)

**Comment by cvvergara** [comment]
The library does not have a version number:
```
more /usr/share/postgresql/12/extension/mobilitydb.control
comment = 'Temporal datatypes and functions'
default_version = '1.0'
module_pathname = '$libdir/libMobilityDB'

requires = 'postgis'
requires = 'postgis'
```

VS for example
```
more /usr/share/postgresql/12/extension/pgrouting.control 
# pgRouting Extension
comment = 'pgRouting Extension'
default_version = '3.2.1'
module_pathname = '$libdir/libpgrouting-3.2'
relocatable = true
requires = 'plpgsql'
requires = 'postgis'
```
OR
```
more /usr/share/postgresql/12/extension/postgis.control 
# postgis extension
comment = 'PostGIS geometry, geography, and raster spatial types and functions'
default_version = '2.5.5'
module_pathname = '$libdir/postgis-2.5'
relocatable = false
```
Also you there is no micro number on the default version

I will add all those things

**Comment by cvvergara** [comment]
This is way way hidden:
```
include/general/temporal.h:#define MOBDB_VERSION_STR "MobilityDB 1.0 beta 3"
```
will put that on the build

**Comment by estebanzimanyi** [comment]
Until I pull the latest PR in my fork the coverage tests were working, and in particular both .gcda and .gcno files were generated. With the new PR the .gcda are missing :-( Any idea why this is the case ? 
Compare the Generate coverage step in the two following runs
https://github.com/estebanzimanyi/MobilityDB/runs/3172150334?check_suite_focus=true
https://github.com/estebanzimanyi/MobilityDB/runs/3172925382?check_suite_focus=true

**Comment by cvvergara** [comment]
@estebanzimanyi 
Please follow this steps: (I am not owner of MobilityDB so I can not do it)
https://docs.transifex.com/transifex-github-integrations/github-tx-ui
So that I can work on uploading automatically the documentation

**Comment by cvvergara** [comment]
BTW
to cleanly update a branch:
add the main repository as upstream:
```
git remote add upstream https://github.com/MobilityDB/MobilityDB
```
Every day I do before I start to work, or when I know there was a change in the main repository:
```
git fetch upstream
```
if the branch where I am going to make a PR to changed, in this case develop branch, I do:
```
git rebase upstream/develop
```
And I make a forced push
```
git push -f
```

**Comment by cvvergara** [comment]
@estebanzimanyi 
How did you generated the pot files that are on transifex?

**Comment by cvvergara** [comment]
https://launchpad.net/ubuntu/+source/gnome-doc-utils/+changelog

**Comment by cvvergara** [comment]
Interesting thing, I am trying to use xml2po but the package where it is, its no longer supported because it uses python2

**Comment by cvvergara** [comment]
I'll close this issue as the documentation is in one directory.
and open one about transifex

**Comment by estebanzimanyi** [comment]
@cvvergara You marked a TODO regarding the xzcat program. Should we use CMake zstd compression ?
https://www.scivision.dev/page/6/
